### PR TITLE
fix(settings-tab): fix background style showing wrong option on render

### LINKED ISSUE #63: Screenshot background style defaults to "Transparent" always
Even after a different value is selected, once plugin settings are closed and re-opened, the drop-down has as default value the "Transparent" value instead of the previously configured value.

### PR DESCRIPTION
**Pull request by james-tindal**
Fixes #63

### CODE REVIEW

File: src/settings-tab.ts [hunk 1]
```diff
@@ -357,6 +357,7 @@ export class MindMapSettingsTab extends PluginSettingTab {
             save();
           })
       );
+    console.log('load', this.plugin.settings.screenshotBgStyle)
```
Comment (MasterTuto) [inline src/settings-tab.ts:360]: - remove `console.log`

**Review by MasterTuto — CHANGES_REQUESTED** [review]
Thanks for making a Pull Request, please, review the changes I requested so I can proceed with your PR.
